name: Build ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt install -y build-essential clang flex bison g++ gawk \
  gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
  python3-venv rsync unzip zlib1g-dev file wget


    - name: Start build
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make -j$(nproc)
