name: Build ImmortalWrt Firmware

on:
  push:
    branches:
      - masterhai  # 替换为你需要的分支，例如 openwrt-23.05
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: masterhai  # 替换为你需要的分支

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib \
          gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file python3 python3-pip subversion swig

      - name: Clone ImmortalWrt source
        run: |
          git clone --depth 1 https://github.com/VIKINGYFY/immortalwrt.git immortalwrt
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build
        run: |
          cd immortalwrt
          # 替换为你的目标设备，例如 x86-64
          echo "CONFIG_TARGET_x86=y" >> .config
          echo "CONFIG_TARGET_x86_64=y" >> .config
          make defconfig

      - name: Compile firmware
        run: |
          cd immortalwrt
          make -j$(nproc) V=s

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-firmware
          path: immortalwrt/bin/targets/
          retention-days: 5
